### ISSUE TITLE
Licensing terms for QMK

### ISSUE THREAD

**Issue by joric** [sekigon-gonnoc/BLE-Micro-Pro#1]
Congratulations, you got hotlinked on Reddit: https://redd.it/ava64y

Great work! I wrote a couple of bluetooth related things (see my github) but never managed to integrate them into QMK.

Could you please specify the licensing terms for your nrf52 fork?
https://github.com/sekigon-gonnoc/qmk_firmware/tree/nrf52

I assume there are no grey zones for this since there's no redistribution of Nordic SDK and everything is on par with GPLv2? Are you going to submit an official pull request to the QMK repository?

**Comment by sekigon-gonnoc** [comment]
At least, I will not submit pull request from nrf52 branch
