### ISSUE TITLE
ブランチ名が間違っている？

### ISSUE THREAD

**Issue by elfmimi** [sekigon-gonnoc/BLE-Micro-Pro#3]
AboutDefaultFirmware/doc/build_bmp_qmk_firmware.md に

> git clone --depth 1 -b nrf52/ble_micro_pro https://github.com/sekigon-gonnoc/qmk_firmware.git qmk_firmware_bmp

とあるのですが
-b dev/ble_micro_pro
の間違いでしょうか？ (それともブランチ名の改名をする予定だったか。)

**Comment by sekigon-gonnoc** [comment]
`-b dev/ble_micro_pro`に修正しました
