### ISSUE TITLE
apidef.h が無い

### ISSUE THREAD

**Issue by elfmimi** [sekigon-gonnoc/BLE-Micro-Pro#4]
以下で include されている apidef.h が存在しないためビルドできません。
https://github.com/sekigon-gonnoc/qmk_firmware/blob/c932f946dab7be602846190d3eb30127ceadf114/tmk_core/protocol/nrf/sdk15/apidef.h#L3

bootloader のアーカイブに含まれているかと考えて探したのですが見つけられませんでした。
https://github.com/sekigon-gonnoc/BLE-Micro-Pro/blob/master/AboutDefaultFirmware/ble_micro_pro_bootloader.zip

**Comment by sekigon-gonnoc** [comment]
修正しました
sekigon-gonnoc/qmk_firmware@b180c463
