### ISSUE TITLE
ビルドガイドの標準のビルド対象について

### ISSUE THREAD

**Issue by elfmimi** [sekigon-gonnoc/BLE-Micro-Pro#5]
ビルドの仕方の案内
https://github.com/sekigon-gonnoc/BLE-Micro-Pro/blob/master/AboutDefaultFirmware/doc/build_bmp_qmk_firmware.md
に

> make &lt;keyboard&gt;:&lt;keymap&gt;:nrfutil

とありますが

> make ble_micro_pro:default:nrfutil

で良いのではないでしょうか？

**Comment by sekigon-gonnoc** [comment]
反映しました
