### ISSUE TITLE
キーコード LCTL_T(KC_TAB)でタップでもプレスでもKC_LCTLが入力される

### ISSUE THREAD

**Issue by hatanoh** [sekigon-gonnoc/BLE-Micro-Pro#7]
KEYMAP.JSNの読み込みでもLCTL_T(KC_TAB)で読めるので、パースは成功しているように見える。
ただし、タップでKC_TABが入力されない。
LSFT_T / RCTL_T でも同様にタップでKCが入力されない。

**Comment by sekigon-gonnoc** [comment]
現在のファームウェアだとソースコード中で設定したTAPPING_TERMは無視されて０になってしまうようです。TAPTERM.JSNにタッピングタームを指定してください。
https://github.com/sekigon-gonnoc/BLE-Micro-Pro/blob/master/AboutDefaultFirmware/doc/getting_start.md#tapping_termjson%E3%81%AE%E8%A8%AD%E5%AE%9A
