### ISSUE TITLE
const key_string_map_t custom_keys_user で最初に登録したキーコードがjsonファイルでは空白になる

### ISSUE THREAD

**Issue by hatanoh** [sekigon-gonnoc/BLE-Micro-Pro#8]
const key_string_map_t custom_keys_user =
{
    .start_kc = NORM,
    .end_kc= cKANA,
    .key_strings =
    "NORM\0ALTN\0"
    "SEL_BLE\0SEL_USB\0TOG_HID\0"
    "xEISU\0xKANA\0"
    "RAISE\0LOWER\0ADJUST\0CONFIG\0"
    "rSPC\0lENT\0lEISU\0lKANA\0cEISU\0cKANA\0"
};
としたとき、KEYMAP.JSN にNORMと書いた箇所が、KEYMAP.JSNを読み出すと""になっている。
NORMのキーコード自体は認識されているようなので、内部テーブルからKEYMAP.JSNを作る時に失敗していそう。

**Comment by sekigon-gonnoc** [comment]
修正しました
